
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpxtymdbkiexqktpkbkl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRweHR5bWRia2lleHFrdHBrYmtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4MTM5MDMsImV4cCI6MjA1NzM4OTkwM30.Ww4A3W0UoXatIz5_MvuR3xN49a40tLXeMFvsHMhFEi8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Stripe publishable key for client-side usage
export const STRIPE_PUBLISHABLE_KEY = import.meta.env.VITE_STRIPE_PUBLISHABLE_KEY || "";
